### ISSUE TITLE
`CP_lroc`, `LP_lroc`, `C_com_lroc` are not saved in master file

### ISSUE THREAD

**Issue by x0range** [Orbis-Amadeus-Oxford/Amadeus-Datawork#8]
`CP_lroc`, `LP_lroc`, `C_com_lroc` are not saved in master file.

Is this on purpose, i.e. are these variables not useful - or should this be included in lines `263` and `267` respectively?

**Comment by yangjh2612** [comment]
Let's discuss what variables we need
